version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NAME=backend
    networks:
      - lyro_network
    restart: always


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NAME=frontend
    networks:
      - lyro_network
    restart: always

networks:
  lyro_network:
    driver: bridge
