export type TasksSeriesType = {
    date: string;
    total_tasks: number;
    total_duration: number;
    total_successful_picks_duration: number;
    total_successful_pick_count: number;
    total_unsuccessful_pick_count: number;
    accumulating_total_tasks: number;
    accumulating_total_duration: number;
    accumulating_total_successful_picks_duration: number;
    accumulating_total_successful_pick_count: number;
    accumulating_total_unsuccessful_pick_count: number;
  };
  export type TasksDataType = {
    series: TasksSeriesType[];
    min_total_tasks: number;
    max_total_tasks: number;
    min_total_duration: number;
    max_total_duration: number;
    min_total_successful_picks_duration: number;
    max_total_successful_picks_duration: number;
    min_total_successful_pick_count: number;
    max_total_successful_pick_count: number;
    min_total_unsuccessful_pick_count: number;
    max_total_unsuccessful_pick_count: number;
    min_accumulating_total_tasks: number;
    max_accumulating_total_tasks: number;
    min_accumulating_total_duration: number;
    max_accumulating_total_duration: number;
    min_accumulating_total_successful_picks_duration: number;
    max_accumulating_total_successful_picks_duration: number;
    min_accumulating_total_successful_pick_count: number;
    max_accumulating_total_successful_pick_count: number;
  };
  export type PicksSeriesType = {
    date: string;
    mpph: number;
    total_duration: number;
    total_picks: number;
    tonnes: number;
    accumulated_total_duration: number;
    accumulated_picks: number;
    accumulated_tonnes: number;
  };
  export type PicksDataType = {
    series: PicksSeriesType[];
    min_mpph: number;
    max_mpph: number;
    min_total_duration: number;
    max_total_duration: number;
    min_total_picks: number;
    max_total_picks: number;
    min_tonnes: number;
    max_tonnes: number;
    min_accumulated_total_duration: number;
    max_accumulated_total_duration: number;
    min_accumulated_picks: number;
    max_accumulated_picks: number;
    min_accumulated_tonnes: number;
    max_accumulated_tonnes: number;
  };